// Export utilities for lessons, quizzes, and flashcards
import { marked } from 'marked';

export function exportAsJSON(data: any, filename: string) {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAsMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAsText(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Convert markdown to HTML for PDF export using the robust `marked` library
 */
function markdownToHTML(markdown: string): string {
  // Configure marked for GitHub Flavored Markdown
  marked.setOptions({
    gfm: true,
    breaks: true
  });
  
  // Convert markdown to HTML using marked (synchronously)
  const html = marked.parse(markdown, { async: false }) as string;
  return html;
}

/**
 * Export lesson content as PDF with proper markdown rendering
 */
export function exportLessonAsPDF(content: string, filename: string) {
  const htmlContent = markdownToHTML(content);
  const printWindow = window.open('', '', 'width=1000,height=800');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <meta charset="utf-8">
      <style>
        @media print {
          @page { margin: 2cm; }
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          line-height: 1.7;
          color: #1a1a1a;
          background: white;
        }
        h1 {
          color: #2563eb;
          font-size: 32px;
          font-weight: 700;
          margin-top: 0;
          margin-bottom: 24px;
          padding-bottom: 12px;
          border-bottom: 3px solid #3b82f6;
        }
        h2 {
          color: #1e40af;
          font-size: 24px;
          font-weight: 600;
          margin-top: 32px;
          margin-bottom: 16px;
          padding-bottom: 8px;
          border-bottom: 2px solid #93c5fd;
        }
        h3 {
          color: #1e3a8a;
          font-size: 20px;
          font-weight: 600;
          margin-top: 24px;
          margin-bottom: 12px;
        }
        p {
          margin-bottom: 16px;
        }
        strong {
          color: #0f172a;
          font-weight: 600;
        }
        em {
          font-style: italic;
          color: #334155;
        }
        code {
          background: #f1f5f9;
          padding: 3px 6px;
          border-radius: 4px;
          font-family: 'Consolas', 'Monaco', monospace;
          font-size: 0.9em;
          color: #dc2626;
        }
        pre {
          background: #1e293b;
          color: #e2e8f0;
          padding: 16px;
          border-radius: 8px;
          overflow-x: auto;
          margin: 20px 0;
        }
        pre code {
          background: none;
          color: inherit;
          padding: 0;
        }
        blockquote {
          border-left: 4px solid #3b82f6;
          padding-left: 20px;
          margin: 20px 0;
          font-style: italic;
          background: #eff6ff;
          padding: 16px 20px;
          border-radius: 4px;
        }
        ul, ol {
          margin: 16px 0;
          padding-left: 30px;
        }
        li {
          margin-bottom: 8px;
          line-height: 1.6;
        }
        .footer {
          margin-top: 60px;
          padding-top: 20px;
          border-top: 2px solid #e5e7eb;
          text-align: center;
          color: #6b7280;
          font-size: 14px;
        }
      </style>
    </head>
    <body>
      ${htmlContent}
      <div class="footer">
        <p>Generated by SlideTutor AI • ${new Date().toLocaleDateString()}</p>
      </div>
      <script>
        window.onload = () => {
          window.print();
          // Close after printing (or cancel)
          setTimeout(() => window.close(), 500);
        };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}

/**
 * Export quiz as PDF with formatted questions and answers
 */
export function exportQuizAsPDF(quiz: any[], filename: string) {
  const questionsHTML = quiz.map((q, index) => {
    const optionsHTML = q.options.map((opt: string, i: number) => {
      const isCorrect = i === q.correctIndex;
      return `
        <div style="padding: 10px; margin: 6px 0; background: ${isCorrect ? '#dcfce7' : '#f9fafb'}; border-left: 4px solid ${isCorrect ? '#22c55e' : '#e5e7eb'}; border-radius: 4px;">
          <strong>${String.fromCharCode(65 + i)}.</strong> ${opt}
          ${isCorrect ? '<span style="color: #16a34a; font-weight: 600; margin-left: 8px;">✓ Correct Answer</span>' : ''}
        </div>
      `;
    }).join('');
    
    return `
      <div style="page-break-inside: avoid; margin-bottom: 40px; padding: 24px; background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
        <div style="color: #3b82f6; font-weight: 700; font-size: 14px; margin-bottom: 8px;">QUESTION ${index + 1}</div>
        <h3 style="color: #0f172a; font-size: 18px; font-weight: 600; margin: 0 0 16px 0;">${q.question}</h3>
        <div style="margin: 16px 0;">
          ${optionsHTML}
        </div>
        <div style="margin-top: 16px; padding: 16px; background: #eff6ff; border-left: 4px solid #3b82f6; border-radius: 4px;">
          <div style="color: #1e40af; font-weight: 600; margin-bottom: 8px;">📘 Explanation:</div>
          <div style="color: #334155; line-height: 1.6;">${q.explanation || 'No explanation provided.'}</div>
        </div>
      </div>
    `;
  }).join('');
  
  const printWindow = window.open('', '', 'width=1000,height=800');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <meta charset="utf-8">
      <style>
        @media print {
          @page { margin: 2cm; }
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          background: #f9fafb;
        }
        h1 {
          color: #2563eb;
          font-size: 32px;
          font-weight: 700;
          margin: 0 0 12px 0;
        }
        .subtitle {
          color: #64748b;
          font-size: 16px;
          margin-bottom: 40px;
        }
        .footer {
          margin-top: 60px;
          padding-top: 20px;
          border-top: 2px solid #e5e7eb;
          text-align: center;
          color: #6b7280;
          font-size: 14px;
        }
      </style>
    </head>
    <body>
      <h1>📝 Quiz</h1>
      <div class="subtitle">${quiz.length} Questions • Generated on ${new Date().toLocaleDateString()}</div>
      ${questionsHTML}
      <div class="footer">
        <p>Generated by SlideTutor AI</p>
      </div>
      <script>
        window.onload = () => {
          window.print();
          setTimeout(() => window.close(), 500);
        };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}

/**
 * Export flashcards as printable PDF with front/back layout
 */
export function exportFlashcardsAsPDF(flashcards: any[], filename: string) {
  const cardsHTML = flashcards.map((card, index) => `
    <div style="page-break-inside: avoid; margin-bottom: 24px;">
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px;">
        <!-- Front of card -->
        <div style="padding: 28px; background: linear-gradient(135deg, #1e40af 0%, #3b82f6 100%); border-radius: 12px; color: #ffffff; min-height: 220px; display: flex; align-items: center; justify-content: center; text-align: center; box-shadow: 0 4px 12px rgba(30,64,175,0.3); border: 3px solid #1e3a8a;">
          <div>
            <div style="font-size: 14px; font-weight: 700; color: #dbeafe; margin-bottom: 12px; letter-spacing: 1px;">FRONT • CARD ${index + 1}</div>
            <div style="font-size: 19px; font-weight: 700; line-height: 1.6; color: #ffffff; text-shadow: 0 1px 2px rgba(0,0,0,0.2);">${card.question}</div>
          </div>
        </div>
        <!-- Back of card -->
        <div style="padding: 28px; background: linear-gradient(135deg, #059669 0%, #10b981 100%); border-radius: 12px; color: #ffffff; min-height: 220px; display: flex; align-items: center; justify-content: center; text-align: center; box-shadow: 0 4px 12px rgba(5,150,105,0.3); border: 3px solid #047857;">
          <div>
            <div style="font-size: 14px; font-weight: 700; color: #d1fae5; margin-bottom: 12px; letter-spacing: 1px;">BACK • CARD ${index + 1}</div>
            <div style="font-size: 17px; font-weight: 600; line-height: 1.7; color: #ffffff; text-shadow: 0 1px 2px rgba(0,0,0,0.2);">${card.answer}</div>
          </div>
        </div>
      </div>
    </div>
  `).join('');
  
  const printWindow = window.open('', '', 'width=1000,height=800');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <meta charset="utf-8">
      <style>
        @media print {
          @page { margin: 1.5cm; }
        }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          max-width: 900px;
          margin: 0 auto;
          padding: 40px 20px;
          background: white;
        }
        h1 {
          color: #2563eb;
          font-size: 32px;
          font-weight: 700;
          margin: 0 0 12px 0;
        }
        .subtitle {
          color: #64748b;
          font-size: 16px;
          margin-bottom: 40px;
        }
        .instructions {
          background: #fef3c7;
          border-left: 4px solid #f59e0b;
          padding: 16px 20px;
          margin-bottom: 32px;
          border-radius: 4px;
        }
        .footer {
          margin-top: 60px;
          padding-top: 20px;
          border-top: 2px solid #e5e7eb;
          text-align: center;
          color: #6b7280;
          font-size: 14px;
        }
      </style>
    </head>
    <body>
      <h1>🎴 Flashcards</h1>
      <div class="subtitle">${flashcards.length} Cards • Generated on ${new Date().toLocaleDateString()}</div>
      <div class="instructions">
        <strong>📌 How to Study:</strong> Cover the answer (right side) and try to recall it from the question (left side). Review cards you get wrong more frequently.
      </div>
      ${cardsHTML}
      <div class="footer">
        <p>Generated by SlideTutor AI</p>
      </div>
      <script>
        window.onload = () => {
          window.print();
          setTimeout(() => window.close(), 500);
        };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}
