import { useState } from 'react';
import { LoginForm } from './LoginForm';
import { RegisterForm } from './RegisterForm';
import { GraduationCap, Brain, Zap, Target, TrendingUp, Award } from 'lucide-react';

export function LandingPage() {
  const [showAuth, setShowAuth] = useState<'login' | 'register' | null>(null);

  if (showAuth === 'login') {
    return <LoginForm onSwitchToRegister={() => setShowAuth('register')} />;
  }

  if (showAuth === 'register') {
    return <RegisterForm onSwitchToLogin={() => setShowAuth('login')} />;
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="gradient-mesh fixed inset-0 opacity-20" />
      
      <div className="relative z-10">
        <header className="container mx-auto px-4 py-6 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <GraduationCap className="w-8 h-8 text-primary" />
            <span className="text-2xl font-bold text-foreground">SlideTutor</span>
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => setShowAuth('login')}
              className="px-6 py-2 text-foreground hover:text-primary transition-colors"
            >
              Log In
            </button>
            <button
              onClick={() => setShowAuth('register')}
              className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors shadow-lg shadow-primary/20"
            >
              Get Started
            </button>
          </div>
        </header>

        <main className="container mx-auto px-4 py-16 md:py-24">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-20">
              <h1 className="text-5xl md:text-7xl font-bold text-foreground mb-8 leading-tight tracking-tight">
                Learn Smarter,
                <br />
                <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                  Not Harder
                </span>
              </h1>
              <p className="text-xl md:text-2xl text-muted-foreground mb-10 max-w-3xl mx-auto leading-relaxed">
                Transform your study materials into interactive lessons, flashcards, and quizzes with AI-powered learning assistance.
              </p>
              <button
                onClick={() => setShowAuth('register')}
                className="px-10 py-4 bg-primary text-white rounded-xl hover:bg-primary/90 transition-all shadow-2xl shadow-primary/30 text-lg font-semibold hover:scale-105 transform duration-200"
              >
                Start Learning Free
              </button>
            </div>

            <div className="grid md:grid-cols-3 gap-10 mb-24">
              <div className="glass-card p-8 rounded-2xl border border-border hover:border-primary/50 transition-all hover:shadow-xl">
                <div className="w-14 h-14 bg-gradient-to-br from-primary to-secondary rounded-xl flex items-center justify-center mb-5">
                  <Brain className="w-7 h-7 text-white" />
                </div>
                <h3 className="text-xl font-bold text-foreground mb-3">AI-Powered Learning</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Upload PDFs, documents, or videos and get instant lessons, quizzes, and flashcards generated by advanced AI.
                </p>
              </div>

              <div className="glass-card p-8 rounded-2xl border border-border hover:border-primary/50 transition-all hover:shadow-xl">
                <div className="w-14 h-14 bg-gradient-to-br from-secondary to-accent rounded-xl flex items-center justify-center mb-5">
                  <Zap className="w-7 h-7 text-white" />
                </div>
                <h3 className="text-xl font-bold text-foreground mb-3">Smart Flashcards</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Spaced repetition system adapts to your learning pace, ensuring you remember what matters most.
                </p>
              </div>

              <div className="glass-card p-8 rounded-2xl border border-border hover:border-primary/50 transition-all hover:shadow-xl">
                <div className="w-14 h-14 bg-gradient-to-br from-accent to-primary rounded-xl flex items-center justify-center mb-5">
                  <Target className="w-7 h-7 text-white" />
                </div>
                <h3 className="text-xl font-bold text-foreground mb-3">Goal Tracking</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Set study goals, track your progress, and build consistent learning habits with our gamified system.
                </p>
              </div>
            </div>

            <div className="glass-card p-12 rounded-3xl border border-border mb-20">
              <div className="grid md:grid-cols-2 gap-12 items-center">
                <div>
                  <h2 className="text-3xl font-bold text-foreground mb-4">
                    Everything You Need to Excel
                  </h2>
                  <p className="text-muted-foreground mb-6">
                    SlideTutor combines the best learning techniques with cutting-edge AI to help you master any subject faster.
                  </p>
                  <div className="space-y-4">
                    <div className="flex items-start gap-3">
                      <div className="w-6 h-6 bg-primary/20 rounded-full flex items-center justify-center mt-1 flex-shrink-0">
                        <div className="w-2 h-2 bg-primary rounded-full" />
                      </div>
                      <div>
                        <h4 className="font-semibold text-foreground mb-1">Interactive Quizzes</h4>
                        <p className="text-sm text-muted-foreground">Test your knowledge with auto-generated questions</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <div className="w-6 h-6 bg-primary/20 rounded-full flex items-center justify-center mt-1 flex-shrink-0">
                        <div className="w-2 h-2 bg-primary rounded-full" />
                      </div>
                      <div>
                        <h4 className="font-semibold text-foreground mb-1">AI Chat Assistant</h4>
                        <p className="text-sm text-muted-foreground">Get instant answers to your study questions</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <div className="w-6 h-6 bg-primary/20 rounded-full flex items-center justify-center mt-1 flex-shrink-0">
                        <div className="w-2 h-2 bg-primary rounded-full" />
                      </div>
                      <div>
                        <h4 className="font-semibold text-foreground mb-1">Progress Analytics</h4>
                        <p className="text-sm text-muted-foreground">Visualize your learning journey with detailed insights</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="glass-card p-6 rounded-xl border border-border text-center">
                    <TrendingUp className="w-8 h-8 text-primary mx-auto mb-2" />
                    <div className="text-2xl font-bold text-foreground mb-1">2x Faster</div>
                    <div className="text-sm text-muted-foreground">Learning speed</div>
                  </div>
                  <div className="glass-card p-6 rounded-xl border border-border text-center">
                    <Award className="w-8 h-8 text-secondary mx-auto mb-2" />
                    <div className="text-2xl font-bold text-foreground mb-1">95%</div>
                    <div className="text-sm text-muted-foreground">Retention rate</div>
                  </div>
                  <div className="glass-card p-6 rounded-xl border border-border text-center col-span-2">
                    <Brain className="w-8 h-8 text-accent mx-auto mb-2" />
                    <div className="text-2xl font-bold text-foreground mb-1">AI-Powered</div>
                    <div className="text-sm text-muted-foreground">Personalized learning</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="text-center">
              <h2 className="text-3xl font-bold text-foreground mb-4">
                Ready to Transform Your Learning?
              </h2>
              <p className="text-muted-foreground mb-8">
                Join thousands of students already learning smarter with SlideTutor
              </p>
              <button
                onClick={() => setShowAuth('register')}
                className="px-8 py-4 bg-primary text-white rounded-xl hover:bg-primary/90 transition-all shadow-xl shadow-primary/30 text-lg font-semibold hover:scale-105 transform duration-200"
              >
                Get Started Free
              </button>
            </div>
          </div>
        </main>

        <footer className="container mx-auto px-4 py-8 mt-20 border-t border-border">
          <div className="text-center text-muted-foreground text-sm">
            <p>&copy; 2025 SlideTutor. Empowering learners worldwide.</p>
          </div>
        </footer>
      </div>
    </div>
  );
}
